sfsapp/urls.py
from django.urls import path
from .views import *


app_name = 'sfsapp'
urlpatterns = [
    path('firstsetup/', FirstSetupView.as_view(), name='firstsetup'),
    path('ordernow/', OrderNowView.as_view(), name='ordernow'),

    path('organization/', OrganizationDetailView.as_view(),
         name='organizationdetail'),
    path('organization/<int:pk>/update/', OrganizationUpdateView.as_view(),
         name='organizationupdate'),

    path('staff-registration/', StaffRegistrationView.as_view(),
         name='staffregistration'),
    path('staff/list/', StaffListView.as_view(), name='stafflist'),
    path('staff/<username>/update/', StaffUpdateView.as_view(),
         name='staffupdate'),
    path('staff/<username>/password/change/',
         StaffPasswordChangeView.as_view(), name='staffpasswordchange'),

    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('home/', HomeView.as_view(), name='home'),
    path('patientnotfound/', PatientNotFoundView.as_view(), name='patientnotfound'),
    path('search/', PatientSearchView.as_view(), name='patientsearch'),
    path('schedule/contact-status/', ChangeContactStatusView.as_view(),
         name='changecontactstatus'),

    path('doctor/list/', DoctorListView.as_view(), name='doctorlist'),
    path('doctor/<slug:slug>/detail/',
         DoctorDetailView.as_view(), name='doctordetail'),
    path('doctor/add/', DoctorCreateView.as_view(), name='doctorcreate'),
    path('doctor/<slug:slug>/update/',
         DoctorUpdateView.as_view(), name='doctorupdate'),
    path('doctor/<slug:slug>/delete/',
         DoctorDeleteView.as_view(), name='doctordelete'),

    path('doctors/schedules/all/', DoctorScheduleListView.as_view(),
         name='doctorschedulelist'),

    path('doctor/<slug:slug>/schedule/<day>/create/',
         DoctorScheduleCreateView.as_view(), name='doctorschedulecreate'),
    path('doctor/<slug:slug>/schedule/<int:pk>/<day>/update/',
         DoctorScheduleUpdateView.as_view(), name='doctorscheduleupdate'),
    path('doctor/<slug:slug>/schedule/<int:pk>/<day>/delete/',
         DoctorScheduleDeleteView.as_view(), name='doctorscheduledelete'),

    path('patient/list/', PatientListView.as_view(), name='patientlist'),
    path('patient/<slug:slug>/detail/',
         PatientDetailView.as_view(), name='patientdetail'),
    path('patient/create/', PatientCreateView.as_view(), name='patientcreate'),
    path('patient/<slug:slug>/update/',
         PatientUpdateView.as_view(), name='patientupdate'),
    path('patient/<slug:slug>/delete/',
         PatientDeleteView.as_view(), name='patientdelete'),

    path('patient/<slug:slug>/refer/', PatientReferView.as_view(),
         name='patientrefer'),


    # Patients Contacted List
    path('get-patients/list/', GetPatientListView.as_view(),
         name='getpatientlist'),


    path('schedule/list/', ScheduleListView.as_view(), name='schedulelist'),
    path('schedule/<slug:slug>/detail/',
         ScheduleDetailView.as_view(), name='scheduledetail'),
    path('schedule/create/', ScheduleCreateView.as_view(),
         name='schedulecreate'),
    path('schedule/<slug:slug>/update/',
         ScheduleUpdateView.as_view(), name='scheduleupdate'),
    path('schedule/<slug:slug>/delete/',
         ScheduleDeleteView.as_view(), name='scheduledelete'),


    path('labtest/list/', LabTestListView.as_view(), name='labtestlist'),
    # path('labtest/<slug:slug>/detail/',
    #      LabTestDetailView.as_view(), name='labtestdetail'),
    path('labtest/create/', LabTestCreateView.as_view(),
         name='labtestcreate'),
    path('labtest/<slug:slug>/update/',
         LabTestUpdateView.as_view(), name='labtestupdate'),
    path('labtest/<slug:slug>/delete/',
         LabTestDeleteView.as_view(), name='labtestdelete'),


    path('activities/list/',
         ActivityListView.as_view(), name='activitylist'),
    path('activities/<slug:slug>/detail/',
         ActivityDetailView.as_view(), name='activitydetail'),
    path('activities/<slug:slug>/update/',
         ActivityUpdateView.as_view(), name='activityupdate'),
    path('activities/<slug:slug>/update/<notlast>/',
         ActivityUpdateView.as_view(), name='activityupdate'),
    path('activities/create/',
         ActivityCreateView.as_view(), name='activitycreate'),
    path('activities/create/<patient_slug>/<id>/',
         ActivityCreateView.as_view(), name='activitycreate'),
    path('activities/<slug:slug>/delete/',
         ActivityDeleteView.as_view(), name='activitydelete'),


    # Transactions
    path('transaction/list/', TransactionListView.as_view(), name='transactionlist'),
    path('transaction/create/', TransactionCreateView.as_view(),
         name='transactioncreate'),
    path('<slug:slug>/transaction/create/',
         TransactionCreateView.as_view(), name='patienttransactioncreate'),
    path('getpreviousdue/',
         GetPreviousDueView.as_view(), name='getpreviousdue'),
    path('transaction/<int:pk>/detail/',
         TransactionDetailView.as_view(), name='transactiondetail'),
    path('<slug:slug>/transaction/list/',
         PatientTransactionListView.as_view(), name='patienttransactionlist'),

    #Account Summary
    path('accountsummary/', AccountSummaryView.as_view(), name='accountsummary'),

]

sfsproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sarobartech.com/sarobartech/', admin.site.urls),
    path('', include('sfsapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sfsapp/models.py
from datetime import datetime, timedelta
import pytz
from django.core.exceptions import ValidationError
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from .utils import unique_slug_generator
from django.db import models


class SoftwareOrder(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    organization = models.CharField(max_length=200, null=True, blank=True)


class Organization(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=10, null=True, blank=True)
    mobile = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    logo = models.ImageField(upload_to="organization", null=True, blank=True)
    image = models.ImageField(upload_to='organization', null=True, blank=True)
    slogan = models.CharField(max_length=400, null=True, blank=True)
    proprietor = models.CharField(max_length=100)
    registered_date = models.DateTimeField(auto_now=True)
    expiry_date = models.DateTimeField()

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     if Organization.objects.exists() and not self.pk:
    #         raise ValidationError(
    #             'Organiztion already added')
    #     return super(Organization, self).save(*args, **kwargs)


class Doctor(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    mobile = models.CharField(max_length=50)
    email = models.EmailField(null=True, blank=True)
    image = models.ImageField(upload_to='doctors', null=True, blank=True)
    speciality = models.CharField(max_length=200)
    education = models.CharField(max_length=200)
    experience = models.FloatField(null=True, blank=True)
    details = models.TextField(null=True, blank=True)
    added_on = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="dcb", null=True, blank=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="dub", null=True, blank=True)

    def __str__(self):
        return self.name + ' ( ' + self.speciality + ' )'

    @property
    def title(self):
        return self.name


DAY = (
    ('sunday', 'sunday'),
    ('monday', 'monday'),
    ('tuesday', 'tuesday'),
    ('wednesday', 'wednesday'),
    ('thursday', 'thursday'),
    ('friday', 'friday'),
    ('saturday', 'saturday'),
)


class DoctorSchedule(models.Model):
    doctor = models.ForeignKey(
        Doctor, on_delete=models.CASCADE, related_name='doctorschedules')
    day = models.CharField(max_length=20, choices=DAY)
    arrival = models.CharField(max_length=30)
    departure = models.CharField(max_length=30)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="dscb", null=True, blank=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="scub", null=True, blank=True)

    def __str__(self):
        return self.doctor.name


GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Others', 'Others'),
)

BLOOD_GROUP = (
    ('A+', 'A+'),
    ('B+', 'B+'),
    ('AB+', 'AB+'),
    ('O+', 'O+'),
    ('A-', 'A-'),
    ('B-', 'B-'),
    ('AB-', 'AB-'),
    ('O-', 'O-'),
)


class Patient(models.Model):
    name = models.CharField(max_length=200)
    patient_code = models.CharField(
        max_length=30, unique=True, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER)
    age = models.PositiveIntegerField()
    blood_group = models.CharField(
        max_length=5, choices=BLOOD_GROUP, null=True, blank=True)
    admitted_on = models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=50)
    email = models.EmailField(null=True, blank=True)
    doctor = models.ForeignKey(
        Doctor, on_delete=models.SET_NULL,
        related_name='docpatients', null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="pcb",

        null=True, blank=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="pub",
        null=True, blank=True)

    total_amount = models.FloatField(default=0)
    paid_amount = models.FloatField(default=0)
    due_amount = models.FloatField(default=0)
    is_referred = models.BooleanField(default=False)
    referred_to = models.CharField(max_length=100, null=True, blank=True)
    referred_on = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)

    @property
    def title(self):
        return self.name

    def __str__(self):
        return self.name + " (Patient Code: " + self.patient_code + ")"

    def save(self):
        self.patient_code = str(self.id)
        return super().save()


class Schedule(models.Model):
    patient = models.ForeignKey(
        Patient, on_delete=models.CASCADE,
        null=True, blank=True, related_name='schedules')
    slug = models.SlugField(unique=True, null=True, blank=True)
    scheduled_on = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=200)
    schedule_date = models.DateTimeField()
    contacted_date = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="scb", null=True, blank=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="sub", null=True, blank=True)
    contacted = models.BooleanField(default=False)
    visited = models.BooleanField(default=False)

    class Meta:
        ordering = ['-schedule_date']

    @property
    def title(self):
        return self.patient.name + "-" + self.subject

    # @property
    # def is_lessthan_3days(self):
    #     return self.schedule_date < datetime.now() + timedelta(days=3)

    def __str__(self):
        return self.patient.name


class LabTest(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, null=True, blank=True)
    charge = models.FloatField(default=0)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="lcb", null=True, blank=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="lub", null=True, blank=True)

    @property
    def title(self):
        return self.name

    def __str__(self):
        return self.name


# class LabTestReport(models.Model):
#     patient = models.ForeignKey(
#         Patient, on_delete=models.CASCADE, related_name='labtestreports')
#     test = models.ForeignKey(LabTest, on_delete=models.SET_NULL,
#                              null=True, related_name='labtestreports')
#     report = models.ImageField(
#         upload_to='labtestreports', null=True, blank=True)
    


class Activity(models.Model):
    patient = models.ForeignKey(
        Patient, on_delete=models.CASCADE, related_name='activities')
    slug = models.SlugField(unique=True, null=True, blank=True)
    doctor = models.ForeignKey(Doctor, null=True,
                               blank=True, on_delete=models.SET_NULL,
                               related_name='activities')
    activity_on = models.DateTimeField(auto_now=True)
    labtest = models.ManyToManyField(
        LabTest, related_name='activities', blank=True)
    report = models.TextField(null=True, blank=True)
    medicines = models.TextField(null=True, blank=True)
    doctor_advice = models.TextField(null=True, blank=True)
    assign_schedule = models.BooleanField(default=False)
    subject = models.CharField(max_length=200, null=True, blank=True)
    next_schedule = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="acb", null=True, blank=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="aub", null=True, blank=True)

    @property
    def title(self):
        return self.patient.name + "-" + "-" + "activity"

    def __str__(self):
        return self.patient.name


PAYMENT_METHOD = (
    ('cash', 'cash'),
    ('check', 'check'),
)


class Transaction(models.Model):
    patient = models.ForeignKey(
        Patient, on_delete=models.SET_NULL, related_name='transactions', null=True)
    deposited_by = models.CharField(max_length=200)
    mobile = models.CharField(max_length=30)
    date = models.DateTimeField(auto_now=True)
    transaction_no = models.PositiveIntegerField(null=True, blank=True)
    service_name = models.CharField(max_length=200)
    doctor_charge = models.FloatField(default=0)
    medicine_charge = models.FloatField(default=0)
    labtest_charge = models.FloatField(default=0)
    misc_charge = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    vat = models.FloatField(default=0)
    net = models.FloatField(default=0)
    advance = models.FloatField(default=0)
    due = models.FloatField(default=0)
    previous_due = models.FloatField(default=0)
    payment_method = models.CharField(
        max_length=20, choices=PAYMENT_METHOD, default='transaction')
    received_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        related_name="transactions", null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):

templates/activitydelete.html
<form class="form" method="POST" action="{% url 'sfsapp:activitydelete' object.slug %}">
	{% csrf_token %}
    <div class="modal-body text-center px-3">
        <h4>Delete {{object.patient.name}} activity?</h4>
    </div>
    <div class="modal-footer px-3 py-2">
        <button class="btn btn-danger w-50 mx-1">Delete</button>
        <button class="btn btn-default w-50 mx-1" data-dismiss="modal">Cancel</button>
    </div>
</form>

templates/activitydetail.html
{% extends 'base.html' %}
{% load static %}
{% block patientlist %}navigation__active{% endblock %}



{% block title %}Patient-{{activitydetail.patient.name}}{% endblock %}

{% block css %}

{% endblock %}


{% block content %}
<div class="card" id="patient-report">
    <div class="card-body">
		<h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Patient Status as on ({{activitydetail.activity_on|date}}): <span style="color: green;">{{activitydetail.name}}</span></h3></h4>
	
		<div class="row">
			<div class="col-md-9 col-sm-12 col-xs-12">
				<table class="table table-bordered table-responsive" style="width: 100%;">
				    <tr>
				        <th>Patient (Code)</th>
				        <td><a href="{% url 'sfsapp:patientdetail' activitydetail.patient.slug %}">{{activitydetail.patient.name|title}} ({{activitydetail.patient.patient_code}})</a></td>
				        <th>Admitted on</th>
						<td>{{activitydetail.activity_on}}</td>
				    </tr>
					<tr>
						<th>Doctor</th>
						<td>{% if activitydetail.doctor %}<a href="{% url 'sfsapp:doctordetail' activitydetail.doctor.slug %}">{{activitydetail.doctor|title}}</a>{% else %}No doctor assigned{% endif %}</td>
						<th>Lab Tests Done</th>
						<td>{% for test in activitydetail.labtest.all %}{% if forloop.counter != 1 %},{% endif %}{{test.name}}  {% endfor %}</td>
					</tr>					
					<tr>
						{% if activitydetail.assign_schedule %}
						<th style="color: #CF1E1E;">Next Followup</th>
						
						<td style="color: #CF1E1E;">{{activitydetail.next_schedule}}</td>
						{% endif %}
						<div id="remove1">
							<th>Last Updated by:</th>
							<td>{{activitydetail.updated_by}}</td>
						</div>
					</tr>
				</table>
			</div>
			<iframe name="print_frame" width="0" height="0" frameborder="0" src="about:blank"></iframe>
			<div class="col-md-3 col-sm-12 col-xs-12" id="remove">
				<a class="d-block-inline btn btn-block bg-brown text-white" href="javascript:printDiv('patient-report')"><i class="zmdi zmdi-print zmdi-hc-fw" style="padding:0 30px 0 0; font-size: 20px;"></i>Print This Report</a>
				<a href="{% url 'sfsapp:activityupdate' activitydetail.slug 'notlast' %}" class="d-block-inline btn btn-block btn-primary" style="margin-bottom: 10px; margin-top: 10px;"><i class="zmdi zmdi-edit zmdi-hc-fw" style="padding:0 30px 0 0; font-size: 20px;"></i>Update This Activity</a>
				{% if request.user.is_staff %}
				<a data-toggle="modal" data-target="#sarobar-modal" data-remote="{% url 'sfsapp:activitydelete' activitydetail.slug %}" href="{% url 'sfsapp:activitydelete' activitydetail.slug %}" class="d-block-inline btn btn-block btn-danger"><i class="zmdi zmdi-close zmdi-hc-fw" style="padding:0 30px 0 0; font-size: 20px;"></i>Delete This Activity</a>
				{% endif %}
			</div>
		</div>
	</div>	
			
    <div class="card-body">
		<h4 class="card-title">Report</h4>
			<p style="text-align: justify;">{{activitydetail.report|safe}}</p>
	</div>
	<div class="card-body">
		<h4 class="card-title">Doctors Advice</h4>
			<p style="text-align: justify;">{{activitydetail.doctor_advice|safe}}</p>
	</div>
	<div class="card-body">
		<h4 class="card-title">Prescribed Medicines</h4>
			<p style="text-align: justify;">{{activitydetail.medicines|safe}}</p>
	</div>
</div>

{% endblock %}

{% block js %}
<!-- <script src="{% static 'jspdf/jspdf.min.js' %}"></script>
<script src="{% static 'jspdf/html2pdf.js' %}"></script> -->

<script type="text/javascript">
    printDivCSS = new String ('<link href="myprintstyle.css" rel="stylesheet" type="text/css">')
    
    function printDiv(divId) {
		$("#remove, #remove1").hide();
        window.frames["print_frame"].document.body.innerHTML=printDivCSS + document.getElementById(divId).innerHTML;
        window.frames["print_frame"].window.focus();
        window.frames["print_frame"].window.print();
		$("#remove, #remove1").show();
    }
</script>


{% endblock %}

templates/base1.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />

    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}">

    {% block css %}

    {% endblock %}
</head>
<body class="container-fluid">
<!-- success message -->
{% if messages %}


<div id="onloadmodal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sarobar System Says!!!</h4>
      </div>
        {% for message in messages %}
      <div class="modal-body bg-{{message.tags}}">
        <p>{{message}}</p>
      </div>
        {% endfor %}
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

{% endif %}

<!-- end of the success message -->
<div class="row" style="margin: 5px 0 0 0;padding: 5px; background-color: black;">
    <div class="col-md-2 col-sm-12" style="margin-top: 5px;">

        <a target="_blank" href="//sarobartech.com"><img src="{% static 'images/sarobarlogo.png' %}" class="img-responsive"></a>
    </div>
    <div class="col-md-2 col-sm-6 col-xs-6" style="margin-top: 15px;">
        <a href="{% url 'sfsapp:patientcreate' %}" class="btn btn-primary btn-block">Admit New Patient</a>
    </div>
    <div class="col-md-2 col-sm-6 col-xs-6" style="margin-top: 15px;">
        <a href="{% url 'sfsapp:doctorcreate' %}" class="btn btn-primary btn-block">Add New Doctor</a><br>
    </div>
    <div class="col-md-2 col-sm-6 col-xs-6" style="margin-top: 15px;">
        <a href="{% url 'sfsapp:labtestcreate' %}" class="btn btn-primary btn-block">Create Labtest</a>
    </div>
    <div class="col-md-2 col-sm-6 col-xs-6" style="margin-top: 15px;">
        <a href="{% url 'sfsapp:staffregistration' %}" class="btn btn-primary btn-block" data-toggle="modal" data-target="#sarobar-modal">Add New Staff</a>
    </div>
    <div class="col-md-2 col-sm-6 col-xs-6" style="margin-top: 15px;">
        <span style="font-size: 15px; color: white;">Logged In As:</span><br>
        <span style="font-size: 18px; color: #BEFFC7;"> {{request.user.username}}</span> 
        <a class="btn btn-danger pull-right" href="{% url 'sfsapp:logout' %}">Logout</a>
        
    </div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-3">
        <nav class="navbar navbar-inverse  navbar-fixed-left">
            <div class="container-fluid">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>
                  <a class="navbar-brand" href="{% url 'sfsapp:organizationdetail' %}"><img src="{% if organization.logo %}{{organization.logo.url}}{% else %}{% static 'images/sarobarlogo.png' %}{% endif %}" width="125"  class="img-responsive" style="margin-left: 60px; margin-top: -10px;"></a>
                </div>
                <br>
                <hr>
                <div class="collapse navbar-collapse navbar-ex1-collapse" id="myNavbar">
                    <ul class="nav navbar-nav" id="navbar-nav">
                        <li class="{% block home %}{% endblock %}"><a href="{% url 'sfsapp:home' %}">Home</a></li>
                        <li class="{% block doctorlist %}{% endblock %}"><a href="{% url 'sfsapp:doctorlist' %}">Doctors</a></li>
                        <li class="{% block doctorschedulelist %}{% endblock %}"><a href="{% url 'sfsapp:doctorschedulelist' %}">Doctors Schedules</a></li>
                        <li class="{% block labtestlist %}{% endblock %}"><a href="{% url 'sfsapp:labtestlist' %}">Lab tests</a></li>
                        <li class="{% block patientlist %}{% endblock %}"><a href="{% url 'sfsapp:patientlist' %}">Patients</a></li>
                        <li class="{% block schedulelist %}{% endblock %}"><a href="{% url 'sfsapp:schedulelist' %}">All Follow Ups</a></li>
                        <li class="{% block activitylist %}{% endblock %}"><a href="{% url 'sfsapp:activitylist' %}">Patients Visits and Reports</a></li>
                        {% if request.user.is_superuser %}
                        <li class="{% block stafflist %}{% endblock %}"><a href="{% url 'sfsapp:stafflist' %}">Staff List</a></li>
                        {% endif %}
                        <br>
                        <li class=""><a href="{% url 'sfsapp:logout' %}">Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="col-md-9 col-sm-9" id="main-content">
        {% block content %}


        {% endblock %}
        
    </div>
</div>
<div id="sarobar-modal" class="modal fade" role="dialog"  data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
          
        </div>
    </div>
</div>


<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

{% block js %}

{% endblock %}
<script type="text/javascript">
    
</script>
<script type="text/javascript">
$('#sarobar-modal').on('hidden.bs.modal', function () {
  location.reload();
})
</script>
<script type="text/javascript">
          $(window).on('load', function(){
            $('#onloadmodal').modal('show');
          });
    </script>
    <script type="text/javascript">
        if (navigator.onLine) {
          console.log('online');
          Response.Redirect("127.0.0.1:8001/admin.aspx?UserName=Imdadhusen&Sex=Male");
        } else {
          console.log('offline');
        }
    </script>
 <!--    <script type="text/javascript">
        string strUser = Request.QueryString["UserName"];
        console.log('strUser');
    </script> -->
</body>
</html>

templates/schedulecreate.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Schedule{% endblock %}

{% block schedulelist %}navigation__active{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'datetimepicker/datetimepicker.min.css' %}">
{% endblock %}

{% block content %}
<div class="card">
  <h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Schedule</h4>
  <div class="card-body">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
        {{form.as_p}}
      <div class="row my-2">
        <button class="btn btn-primary text mx-auto" style="width:200px;">Submit</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
    $("#id_patient").parent().hide();
</script>

<script type="text/javascript">
  $("#id_schedule_date").click(function() {
      $('html,body').animate({
          scrollTop: 300 },
          'slow');
  });
</script>

{% endblock %}