sfsapp/urls.py
from django.urls import path
from .views import *


app_name = 'sfsapp'
urlpatterns = [
    path('firstsetup/', FirstSetupView.as_view(), name='firstsetup'),
    path('ordernow/', OrderNowView.as_view(), name='ordernow'),

    path('organization/', OrganizationDetailView.as_view(),
         name='organizationdetail'),
    path('organization/<int:pk>/update/', OrganizationUpdateView.as_view(),
         name='organizationupdate'),

    path('staff-registration/', StaffRegistrationView.as_view(),
         name='staffregistration'),
    path('staff/list/', StaffListView.as_view(), name='stafflist'),
    path('staff/<username>/update/', StaffUpdateView.as_view(),
         name='staffupdate'),
    path('staff/<username>/password/change/',
         StaffPasswordChangeView.as_view(), name='staffpasswordchange'),

    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('home/', HomeView.as_view(), name='home'),
    path('patientnotfound/', PatientNotFoundView.as_view(), name='patientnotfound'),
    path('search/', PatientSearchView.as_view(), name='patientsearch'),
    path('schedule/contact-status/', ChangeContactStatusView.as_view(),
         name='changecontactstatus'),

    path('doctor/list/', DoctorListView.as_view(), name='doctorlist'),
    path('doctor/<slug:slug>/detail/',
         DoctorDetailView.as_view(), name='doctordetail'),
    path('doctor/add/', DoctorCreateView.as_view(), name='doctorcreate'),
    path('doctor/<slug:slug>/update/',
         DoctorUpdateView.as_view(), name='doctorupdate'),
    path('doctor/<slug:slug>/delete/',
         DoctorDeleteView.as_view(), name='doctordelete'),

    path('doctors/schedules/all/', DoctorScheduleListView.as_view(),
         name='doctorschedulelist'),

    path('doctor/<slug:slug>/schedule/<day>/create/',
         DoctorScheduleCreateView.as_view(), name='doctorschedulecreate'),
    path('doctor/<slug:slug>/schedule/<int:pk>/<day>/update/',
         DoctorScheduleUpdateView.as_view(), name='doctorscheduleupdate'),
    path('doctor/<slug:slug>/schedule/<int:pk>/<day>/delete/',
         DoctorScheduleDeleteView.as_view(), name='doctorscheduledelete'),

    path('patient/list/', PatientListView.as_view(), name='patientlist'),
    path('patient/<slug:slug>/detail/',
         PatientDetailView.as_view(), name='patientdetail'),
    path('patient/create/', PatientCreateView.as_view(), name='patientcreate'),
    path('patient/<slug:slug>/update/',
         PatientUpdateView.as_view(), name='patientupdate'),
    path('patient/<slug:slug>/delete/',
         PatientDeleteView.as_view(), name='patientdelete'),

    path('patient/<slug:slug>/refer/', PatientReferView.as_view(),
         name='patientrefer'),


    # Patients Contacted List
    path('get-patients/list/', GetPatientListView.as_view(),
         name='getpatientlist'),


    path('schedule/list/', ScheduleListView.as_view(), name='schedulelist'),
    path('schedule/<slug:slug>/detail/',
         ScheduleDetailView.as_view(), name='scheduledetail'),
    path('schedule/create/', ScheduleCreateView.as_view(),
         name='schedulecreate'),
    path('schedule/<slug:slug>/update/',
         ScheduleUpdateView.as_view(), name='scheduleupdate'),
    path('schedule/<slug:slug>/delete/',
         ScheduleDeleteView.as_view(), name='scheduledelete'),


    path('labtest/list/', LabTestListView.as_view(), name='labtestlist'),
    # path('labtest/<slug:slug>/detail/',
    #      LabTestDetailView.as_view(), name='labtestdetail'),
    path('labtest/create/', LabTestCreateView.as_view(),
         name='labtestcreate'),
    path('labtest/<slug:slug>/update/',
         LabTestUpdateView.as_view(), name='labtestupdate'),
    path('labtest/<slug:slug>/delete/',
         LabTestDeleteView.as_view(), name='labtestdelete'),


    path('activities/list/',
         ActivityListView.as_view(), name='activitylist'),
    path('activities/<slug:slug>/detail/',
         ActivityDetailView.as_view(), name='activitydetail'),
    path('activities/<slug:slug>/update/',
         ActivityUpdateView.as_view(), name='activityupdate'),
    path('activities/<slug:slug>/update/<notlast>/',
         ActivityUpdateView.as_view(), name='activityupdate'),
    path('activities/create/',
         ActivityCreateView.as_view(), name='activitycreate'),
    path('activities/create/<patient_slug>/<id>/',
         ActivityCreateView.as_view(), name='activitycreate'),
    path('activities/<slug:slug>/delete/',
         ActivityDeleteView.as_view(), name='activitydelete'),


    # Transactions
    path('transaction/list/', TransactionListView.as_view(), name='transactionlist'),
    path('transaction/create/', TransactionCreateView.as_view(),
         name='transactioncreate'),
    path('<slug:slug>/transaction/create/',
         TransactionCreateView.as_view(), name='patienttransactioncreate'),
    path('getpreviousdue/',
         GetPreviousDueView.as_view(), name='getpreviousdue'),
    path('transaction/<int:pk>/detail/',
         TransactionDetailView.as_view(), name='transactiondetail'),
    path('<slug:slug>/transaction/list/',
         PatientTransactionListView.as_view(), name='patienttransactionlist'),

    #Account Summary
    path('accountsummary/', AccountSummaryView.as_view(), name='accountsummary'),

]

sfsproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sarobartech.com/sarobartech/', admin.site.urls),
    path('', include('sfsapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/transactions/accountsummary.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Account Summary{% endblock %}

{% block accountsummary %}navigation__active{% endblock %}


{% block css %}

{% endblock %}

{% block content %}

<div class="card">
  <div class="card-body">
    <h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Due Amount List</h4>
    <div class="table-responsive">
      <table id="data-table" class="table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient Name</th>
            <th>Mobile</th>
            <th>Due Amount</th>
          </tr>
        </thead>
        <tfoot class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient Name</th>
            <th>Mobile</th>
            <th>Due Amount</th>
          </tr>
        </tfoot>
        <tbody>
          {% for patient in patientswithdue %}
          <tr>
            <td id="first-column" style="width: 80px;">{{forloop.counter}}</td>
            <td><a href="{% url 'sfsapp:patientdetail' patient.slug %}">{{patient.name|title}} ({{patient.patient_code}})</a></td>
            <td class="big-text">{{patient.mobile}}</td>
            <td class="big-text">{{patient.due_amount}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}

<script type="text/javascript" src="{% static 'datetimepicker/datetimepicker.min.js' %}"></script>
<script type="text/javascript">
  var date = new Date(), y = date.getFullYear(), m = date.getMonth();
  var firstDay = new Date(y, m, 1);
  var lastDay = new Date(y, m + 1, 0);
  // var mydate = $("#from_date").bind("change paste keyup", function() {
  //              var mindate = $('#from_date').val();
  //              return mindate
  //           });


    $(".from_date").flatpickr({
      allowInput:false,
      maxDate:"today",
      defaultDate: {% if request.GET %}"{{request.GET.from_date}}"{% else %}firstDay{% endif %}, 
    });
    $(".to_date").flatpickr({
      allowInput:false,
      minDate:"",
      maxDate: lastDay,
      defaultDate: {% if request.GET %}"{{request.GET.to_date}}"{% else %}lastDay{% endif %},
    });
</script>
{% endblock %}

templates/transactions/getpreviousdue.html
{{previous_due}}

templates/transactions/patienttransactionlist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Patient Transaction List{% endblock %}

{% block patientlist %}navigation__active{% endblock %}


{% block css %}

{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h4 class="mb-4 px-3 py-3 bg-success text-white">Patient's Account Summary</h4>
    <div class="row">
      <div class="col-md-4 col-sm-12 col-xs-12">
          <h4 class="text-secondary">Total Amount</h4><hr>
          <h5 class="text-primary">Rs. {{patientdetail.total_amount}}/-</h5>          
      </div>
      <div class="col-md-4 col-sm-12 col-xs-12">
          <h4 class="text-secondary">Total Paid Amount</h4><hr>
          <h5 class="text-success">Rs. {{patientdetail.paid_amount}}/-</h5>          
      </div>
      <div class="col-md-4 col-sm-12 col-xs-12">
          <h4 class="text-secondary">Total Due Amount</h4>   <hr>
          <h5 class="text-danger">Rs. {{patientdetail.due_amount}}/-</h5>          
      </div>
    </div>
  </div>
  <div class="card-body">
    <h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Transaction List</h4>
    <div class="table-responsive">
      <a style="width:200px;" class="my-2 btn btn-primary" href="{% url 'sfsapp:patienttransactioncreate' patientdetail.slug %}">Add Transaction</a>
        
      <table id="data-table" class="table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient</th>
            <th style="width: 135px;">Amount</th>
            <th>Deposited By</th>
            <th style="width: 100px;">Date</th>
            <th style="width: 130px;">Previous Due</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
            <th style="width: 130px;">Received By</th>
          </tr>
        </thead>
        <tfoot class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient</th>
            <th style="width: 135px;">Amount</th>
            <th>Deposited By</th>
            <th style="width: 100px;">Date</th>
            <th style="width: 130px;">Previous Due</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
            <th style="width: 130px;">Received By</th>
          </tr>
        </tfoot>
        <tbody>
          {% for transaction in patientdetail.transactions.all %}
          <tr>
            <td id="first-column" style="width: 80px;">{{forloop.counter}}</td>
            <td><a href="{% url 'sfsapp:transactiondetail' transaction.id %}">{{transaction.patient.name|title}}</a></td>
            <td>{{transaction.net}}</td>
            <td>{{transaction.deposited_by}}</td>
            <td style="width: 135px;" class="big-text">{{transaction.date}}</td>
            <td class="big-text" style="width: 100px;">{{transaction.previous_due}}</td>
            <td class="big-text">{{transaction.advance}}</td>
            <td class="big-text">{{transaction.due}}</td>
            <td style="width: 130px;">{{transaction.received_by}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

{% block js %}

{% endblock %}

templates/transactions/transactioncreate.html
{% extends '../base.html' %}
{% load static %}

{% block title %}Transaction{% endblock %}

{% block transactionparentdropdownstatus %}navigation__sub--active navigation__sub--toggled{% endblock %}
{% block transactioncreate %}navigation__active{% endblock %}


{% block css %}

<style>
  .form-element {
    /*border: 0px solid #888;*/
    padding: 10px 10px 10px 10px;
    display: inline;
  }
  .form-element span {
    margin: 0 5px;
    display: inline-block;
  }
  .form-element .form-control {
    margin: 0 5px;
    display: inline-block;
  }
  .text-input, option {
    border: 1px solid;
    padding-left: 20px;
  }
  .number-input {
    border: 1px solid;
    -moz-appearance: textfield;
    text-align: right;
    padding-left: 20px;
    padding-right: 20px;
  }

  .text-input:focus {
    border: 1px solid;
    background-color: #F9E79F;
  }
  .number-input:focus {
    border: 1px solid;
    background-color: #F9E79F;
  } 
  .number-input::-webkit-outer-spin-button,
  .number-input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
  }

  .select2 {
    border: 1px solid;
    width:50%;
  }

</style>
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <!-- <h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Transaction</h4> -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container-fluid">
          <div class="row py-2 text-center" style="background-color: #2299a3;">
            <h4 class="col-12 text-white">{{organization.name}}</h4>
            <br>
            <h5 class="col-12 text-white">Transaction</h5>
          </div>
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12 py-4 px-3 bg-light">
              <div class="my-3 py-2">
                Patient Name: {{form.patient}}
                <span style="position: absolute;" class="text-danger">{{form.patient.errors}}</span>
              </div>
              <div class="my-3 py-2">
                Service Name: {{form.service_name}}
                <span style="position: absolute;" class="text-danger">{{form.service_name.errors}}</span>
              </div>
              <div class="my-3 py-2">
                Mobile: {{form.mobile}}
                <span style="position: absolute;" class="text-danger">{{form.mobile.errors}}</span>
              </div>
            </div>
            <!-- <div class="col-md-2 hidden-sm hidden-xs py-2 px-2 bg-light">
            </div> -->
            <div class="col-md-6 col-sm-6 col-xs-12 py-4 px-3 bg-light">
              <div class="my-3 py-2">
                Payment Method: {{form.payment_method}}
                <span style="position: absolute;" class="text-danger">{{form.payment_method.errors}}</span>
              </div>
              <div class="my-3 py-2">
                Cash Deposited By: {{form.deposited_by}}
                <span style="position: absolute;" class="text-danger">{{form.deposited_by.errors}}</span>
              </div>
            </div>
          </div>
          <div class="row my-2" style="border: 1px solid grey;">
            <div class="table-responsive" style="background-color: #fff1f1;">
              <table id="transaction-datatable" class="table table-bordered">
                <thead class="table-secondary">
                  <tr>
                    <th id="first-column" style="width: 80px;">SN</th>
                    <th style="width: 250px;">Service</th>
                    <th style="width: 135px;">Charge</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td id="first-column" style="width: 80px;">1</td>
                    <td style="width: 250px;">Doctor Charge</td>
                    <td style="width: 135px;">
                      {{form.doctor_charge}}
                      <span style="position: absolute;" class="text-danger">{{form.doctor_charge.errors}}</span>
                    </td>
                  </tr>
                  <tr>
                    <td id="first-column" style="width: 80px;">2</td>
                    <td style="width: 250px;">Lab Test Charge</td>
                    <td style="width: 135px;">
                      {{form.labtest_charge}}
                      <span style="position: absolute;" class="text-danger">{{form.labtest_charge.errors}}</span>
                    </td>
                  </tr>
                  <tr>
                    <td id="first-column" style="width: 80px;">3</td>
                    <td style="width: 250px;">Medicine Charge</td>
                    <td style="width: 135px;">
                      {{form.medicine_charge}}
                      <span style="position: absolute;" class="text-danger">{{form.medicine_charge.errors}}</span>
                    </td>
                  </tr>
                  <tr>
                    <td id="first-column" style="width: 80px;">4</td>
                    <td style="width: 250px;">Miscellaneous Charge</td>
                    <td style="width: 135px;">
                      {{form.misc_charge}}
                      <span style="position: absolute;" class="text-danger">{{form.misc_charge.errors}}</span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="row py-3" style="background-color: #f1f1ff;">
            <div class="col-md-6 col-sm-6 col-xs-12">
              Description:
              {{form.description}}
            <span style="position: absolute;" class="text-danger">{{form.description.errors}}</span>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <h5>Sub Total <span class="float-right pr-3" id="total"></span></h5>
              <div class="">
                <span style="width:50%; float: left;">Discount</span> 
                {{form.discount}}
                <span style="position: absolute;" class="text-danger">{{form.discount.errors}}</span>
              </div>
              <div class="my-1">
                <span style="width:50%; float: left;">VAT (%)</span>
                {{form.vat}}
                <span style="position: absolute;" class="text-danger">{{form.discount.errors}}</span>
              </div>
              <div class="my-1">
                <span style="width:50%; float: left; font-weight: 600;">Net Total</span>
                {{form.net}}
                <span style="position: absolute;" class="text-danger">{{form.net.errors}}</span>
              </div>
              <div class="my-1">
                <span style="width:50%; float: left;">Advance Payment</span>
                {{form.advance}}
                <span style="position: absolute;" class="text-danger">{{form.advance.errors}}</span>
              </div>
              <div class="my-1">
                <span style="width:50%; float: left;">Previous Due</span>
                {{form.previous_due}}
                <span style="position: absolute;" class="text-danger">{{form.previous_due.errors}}</span>
              </div>
              <div class="my-1 text-danger">
                <span style="width:50%; float: left;">Remaining Due</span>
                {{form.due}}
                <span style="position: absolute;" class="text-danger">{{form.due.errors}}</span>
              </div>            
            </div>
          </div>
        </div>
  		<div class="row my-3">
  			<button class="btn btn-primary text mx-auto" style="width:200px;">Submit</button>
  		</div>
    </form>
  </div>
</div>

{% endblock %}


{% block js %}

<script type="text/javascript">
  
</script>

<script type="text/javascript">
  {% if view.kwargs.slug %}
    document.getElementById('id_patient').parentElement.style.display = 'none';
    document.getElementById('id_patient').value = '{{thispatient_id}}';
    document.getElementById('id_previous_due').value = '{{thispatientdue}}';
  {% else %}

	$('#id_patient').change(function(){
		var url = {% url 'sfsapp:getpreviousdue' %};
		var patient_id = $(this).val();
		$.ajax({            
	      url: url,                   
	      data: {
	        'patient_id':patient_id,
	      },
	      success: function (data) {
	        $("#id_previous_due").val(data);
	      }
	    });
	});
  {% endif %}
	
	function findTotal(){
		var doctor_charge = parseInt(document.getElementById("id_doctor_charge").value);
		var medicine_charge = parseInt(document.getElementById("id_medicine_charge").value);
		var labtest_charge = parseInt(document.getElementById("id_labtest_charge").value);
		var misc_charge = parseInt(document.getElementById("id_misc_charge").value);
		var discount = parseInt(document.getElementById("id_discount").value);
		var vat = parseInt(document.getElementById("id_vat").value);
		var previous_due = parseInt(document.getElementById("id_previous_due").value);
		var advance = parseInt(document.getElementById("id_advance").value);
		if(!doctor_charge){doctor_charge=0}
		if(!medicine_charge){medicine_charge=0}
		if(!labtest_charge){labtest_charge=0}
		if(!misc_charge){misc_charge=0}
		if(!discount){discount=0}
		if(!vat){vat=0}
		if(!advance){advance=0}
		if(!previous_due){previous_due=0}
		
		var total = doctor_charge + medicine_charge + labtest_charge + misc_charge;
		document.getElementById('total').innerHTML ="Rs. " + total;
		var discounted_amount = total - discount;
    var vat_amt = vat/100 * discounted_amount;
		var net = discounted_amount + vat_amt;
    document.getElementById('id_vat').value = vat;
    document.getElementById('id_net').value = net;
    document.getElementById('id_due').value = net - advance + previous_due;
	}
</script>

<script type="text/javascript">
  $(".form-input-text-select").click(function () {
    $(this).select();
  });

  $(':input[type=number]').on('mousewheel', function(e){
    e.preventDefault();
  });
  $('.form-input-text-select').change(function(){
    var value = $(this).val();
    if (value == '') {
      $(this).val(0);
    }
  });
</script>

{% endblock %}

templates/transactions/transactionlist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Transaction List{% endblock %}

{% block transactionparentdropdownstatus %}navigation__sub--active navigation__sub--toggled{% endblock %}
{% block transactionlist %}navigation__active{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Account Information Summary</h4>
    <div class="row">
      <div class="col-md-4 col-sm-12 col-xs-12">
          <h4 class="text-secondary">Total Transaction Amount</h4><hr>
          <h5 class="text-primary">Rs. {{total_amount}}/-</h5>          
      </div>
      <div class="col-md-4 col-sm-12 col-xs-12">
          <h4 class="text-secondary">Total Paid Amount</h4><hr>
          <h5 class="text-success">Rs. {{paid_amount}}/-</h5>          
      </div>
      <div class="col-md-4 col-sm-12 col-xs-12">
          <h4 class="text-secondary">Total Due Amount</h4><hr>
          <h5 class="text-danger">Rs. {{due_amount}}/- <a class="btn btn-sm btn-info" href="{% url 'sfsapp:accountsummary' %}">See Detail</a></h5>          
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Account Information related to Patient</h4>
    <div class="table-responsive">
      <table id="data-table" class="table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient</th>
            <th>Total Amount</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
          </tr>
        </thead>
        <tfoot class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient</th>
            <th>Total Amount</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
          </tr>
        </tfoot>
        <tbody>
          {% for patient in patientlist %}
          <tr>
            <td id="first-column" style="width: 80px;">{{forloop.counter}}</td>
            <td><a href="{% url 'sfsapp:patienttransactionlist' patient.slug %}">{{patient.name|title}}</a></td>
            <td>{{patient.total_amount}}</td>
            <td>{{patient.paid_amount}}</td>
            <td>{{patient.due_amount}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h4 class="mb-4 px-3 py-3 bg-success text-white" style="border-radius:2px; color: #333; font-weight: 400;">Transaction List</h4>
    <div class="table-responsive">
      <a style="width:150px;" class="my-2 btn btn-primary" href="{% url 'sfsapp:transactioncreate' %}">Add Transaction</a>
      <table id="data-table1" class="table table-bordered">
        <thead class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient</th>
            <th style="width: 135px;">Amount</th>
            <th style="width: 140px;">Deposited By</th>
            <th style="width: 100px;">Date</th>
            <th style="width: 130px;">Previous Due</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
            <th style="width: 130px;">Received By</th>
          </tr>
        </thead>
        <tfoot class="table-secondary">
          <tr>
            <th id="first-column" style="width: 80px;">SN</th>
            <th>Patient</th>
            <th style="width: 135px;">Amount</th>
            <th style="width: 140px;">Deposited By</th>
            <th style="width: 100px;">Date</th>
            <th style="width: 130px;">Previous Due</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
            <th style="width: 130px;">Received By</th>
          </tr>
        </tfoot>
        <tbody>
          {% for transaction in transactionlist %}
          <tr>
            <td id="first-column" style="width: 80px;">{{forloop.counter}}</td>
            <td><a href="{% url 'sfsapp:transactiondetail' transaction.id %}">{{transaction.patient.name|title}}</a></td>
            <td>{{transaction.net}}</td>
            <td>{{transaction.deposited_by}}</td>
            <td style="width: 135px;" class="big-text">{{transaction.date}}</td>
            <td class="big-text" style="width: 100px;">{{transaction.previous_due}}</td>
            <td class="big-text">{{transaction.advance}}</td>
            <td class="big-text">{{transaction.due}}</td>
            <td style="width: 130px;">{{transaction.received_by}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}

{% endblock %}